name: Update Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install github-changelog-generator
      run: |
        gem install github_changelog_generator

    - name: Generate CHANGELOG.md
      run: |
        github_changelog_generator --user ${{ github.repository_owner }} --project ${{ github.event.repository.name }} --token ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push updated CHANGELOG
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/CHANGELOG.md
        git commit -m "Update CHANGELOG.md [skip ci]" || echo "No changes to commit"
        git push origin main
